<?php $order = $block->getViewModel()->getOrder() ?>
<?php if (!$order->getId()): ?>
    <p><?php echo __('Order does not exist') ?></p>
<?php else: ?>
    <ul>
        <li><strong><?php echo __('Order Status') ?>:</strong> <?php echo $order->getStatus() ?></li>
        <li><strong><?php echo __('Order Total') ?>:</strong> <?php echo $order->getGrandTotal() ?></li>
        <li><strong><?php echo __('Order Total Invoiced') ?>:</strong> <?php echo $order->getTotalInvoiced() ?></li>
    </ul>
<?php endif; ?>
